apiVersion: v1
kind: Pod
metadata:
  name: producer
spec:
  containers:
  - name: ubuntu
    command:
    - tail
    - -f
    - /dev/null
    image: ubuntu
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data

